name: JoinPreference
description: Gives preference in a full server to designated groups.
author: FearMig
website: www.GorillaCraft.com
version: 1.2
main: org.mig.joinpreference.joinPreference

commands:
  jpref:
    description: JoinPreference commands